services:
  - type: web
    name: mounir-cutzz-ai-receptionist
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-receptionist-redis
          property: connectionString
      - key: BARBER_SHOP_NAME
        value: "Mounir Cutzz"
      - key: BARBER_SHOP_TIMEZONE
        value: "Asia/Beirut"
      - key: WEBHOOK_BASE_URL
        fromService:
          type: web
          name: mounir-cutzz-ai-receptionist
          property: host

  - type: redis
    name: ai-receptionist-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
